name: Keystone CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/  
    - name: git setup
      run: |
        git config --local user.email sam@wearedevx.com
        git config --local user.name devx-opensource
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: install global dependencies
      run: |
        npm add -g pnpm
        npm add -g @microsoft/rush
        npm install -g oclif-dev-cli-npm
        sudo apt-get install p7zip-full
    - name: rush install, build
      # create an empty env to avoid warnings and process.exit = 1 on rush build
      run: |
        touch keystone-web/.env 
        rush install
        rush build
    - name: run @keystone/cli tests suite
      run: |
        rush test
    - name: rush publish
      run: |
        rush publish -a -b master -p --set-access-level public --add-commit-details
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: Deploy on Zeit - Prod
      uses: wearedevx/now-deployment@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        zeit-team-id: team_JUoHyeXny2vWE50ne05TjfId
        now-folder-path: ./keystone-web/dist
        now-args: '--local-config=../now.json --prod -c'
